## Numpy

Mirar los videos que están en la plataforma de Acámica y tratar de resolver los siguientes ejercicios y preguntas. La documentación de Numpy es muy buena, recomendamos ir familiarizándose con ella.

### Repaso

Importamos la librería

In [1]:
import numpy as np

A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Algunas cosas que no se podían hacer con las listas ahora sí se pueden:

1. Sumarle un mismo elemento a toda la lista

In [4]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
arreglo + 2

2. Elevar al cuadrado todos los elementos de una lista

In [ ]:
lista**2

In [ ]:
arreglo**2

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [ ]:
arr1 = range(8) 

In [ ]:
arr2 = np.arange(8)

In [ ]:
arr2 == arr1  

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [ ]:
a = np.arange(10)

In [ ]:
a

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50.

In [5]:
a = np.arange(10,100)
mask = a<50

print(a[mask])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
a = np.arange(10,100)
mask = a<50

print(a[mask])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [7]:
arr = np.zeros((5, 10))

In [8]:
arr[1:4:2] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr[::,2] = 2
arr[::,7] = 2

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

In [10]:
arr

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

In [11]:
arr[:, [2,7]] = 3

In [12]:
arr

array([[0., 0., 3., 0., 0., 0., 0., 3., 0., 0.],
       [1., 1., 3., 1., 1., 1., 1., 3., 1., 1.],
       [0., 0., 3., 0., 0., 0., 0., 3., 0., 0.],
       [1., 1., 3., 1., 1., 1., 1., 3., 1., 1.],
       [0., 0., 3., 0., 0., 0., 0., 3., 0., 0.]])

In [15]:
s = np.arange(2,100,3.5)

In [16]:
s


array([ 2. ,  5.5,  9. , 12.5, 16. , 19.5, 23. , 26.5, 30. , 33.5, 37. ,
       40.5, 44. , 47.5, 51. , 54.5, 58. , 61.5, 65. , 68.5, 72. , 75.5,
       79. , 82.5, 86. , 89.5, 93. , 96.5])