In [13]:
import numpy as np

In [14]:
data = np.random.randn(2,3)

In [15]:
data

array([[ 0.04298912, -0.82793896, -1.46280658],
       [-1.85560886,  0.67027821,  0.9962516 ]])

In [16]:
data + data


array([[ 0.08597824, -1.65587791, -2.92561316],
       [-3.71121771,  1.34055642,  1.99250321]])

In [17]:
data = [[1,2,3],[2,1]]

In [18]:
data

[[1, 2, 3], [2, 1]]

In [19]:
array2 = np.array(data)

In [20]:
array2

array([list([1, 2, 3]), list([2, 1])], dtype=object)

In [21]:
print(array2.shape)

(2,)


In [22]:
print(array2.ndim)

1


In [47]:
arr = np.arange(99,30, -1)

In [48]:
arr

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31])

In [25]:
arr[5]

5

In [26]:
arr[2:5]

array([2, 3, 4])

In [27]:
arr[:] = 58

In [28]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

In [61]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr[1,:1]

array([4])

In [64]:
a = range(4)

In [65]:
a


range(0, 4)

In [66]:
for b in a:
    print(b)

0
1
2
3


In [67]:
arr = np.arange(20)

In [68]:
arr[2:20:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
[x + x for x in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [72]:
arreglo2d = np.arange(56).reshape(8,7)

In [75]:
mask = arreglo2d % 2 == 0

In [76]:
mask

array([[ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])

In [77]:
arreglo2d[mask]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

In [80]:
arreglo2d = np.arange(9).reshape(3,3)

In [81]:
arreglo2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
arreglo2d.sum()

36

In [85]:
arreglo2d.sum(axis = 0)

array([ 9, 12, 15])

In [88]:
arreglo2d.sum(axis = 1)

array([ 3, 12, 21])