## Un poco de Slicing & Indexing

La sintaxis básica de corte es i: j: k donde:  
+ i: índice inicial
+ j: índice de detención
+ k: es el paso (k <> 0)

Esto selecciona los elementos (en la dimensión correspondiente) con valores de índice $i, i + k, ..., i + (m - 1) k$ 

#### 1.- Generaremos un array con los números del 0 al 15  
_cada nro. corresponde al indice a su indice en el array_

In [1]:
import numpy as np

arr1 = np.arange(16)

print('Array de 0 a 15 (k=1):')
arr1

Array de 0 a 15 (k=1):


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
print('Selecciono el 1er. elemento:')
arr1[0]

Selecciono el 1er. elemento:


0

In [3]:
print('Selecciono el 2do. elemento:')
arr1[1]

Selecciono el 2do. elemento:


1

In [4]:
print('Selecciono el último elemento:')
arr1[15]

Selecciono el último elemento:


15

In [5]:
print('Otra forma de seleccion el último elemento:')
arr1[-1]

Otra forma de seleccion el último elemento:


15

In [6]:
print('Selecciono del 6to. al 11vo. elemento:')
arr1[5:11]

Selecciono del 6to. al 11vo. elemento:


array([ 5,  6,  7,  8,  9, 10])

In [7]:
print('Selecciono los nros. impares, indicando el paso (k):')
arr1[1:16:2]

Selecciono los nros. impares, indicando el paso (k):


array([ 1,  3,  5,  7,  9, 11, 13, 15])

#### indices negativos  
i y j negativos se interpretan como $n + i$ y $n + j$  
donde $n$ es el número de elementos en la dimensión correspondiente.   

In [8]:
i = -5
print('i negativo:')
arr1[i:]

i negativo:


array([11, 12, 13, 14, 15])

In [9]:
n = len(arr1)
print('Lo que equivale a (n + i):')
arr1[n+i:]

Lo que equivale a (n + i):


array([11, 12, 13, 14, 15])

In [10]:
j = -5
print('j negativo:')
arr1[:j]

j negativo:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
print('lo que equivale a (n + j):')
arr1[:n+j]

lo que equivale a (n + j):


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
i = -10
j = -4

print('i y j negativos:')
arr1[i:j]

i y j negativos:


array([ 6,  7,  8,  9, 10, 11])

In [13]:
print('lo que equivale a (n+i:n+j)')
arr1[n+i:n+j]

lo que equivale a (n+i:n+j)


array([ 6,  7,  8,  9, 10, 11])

k negativo hace que el paso hacia índices más pequeños.

In [14]:
print('k negativo:')
arr1[12:7:-1]

k negativo:


array([12, 11, 10,  9,  8])

In [15]:
print('i,j,k negativo:')
arr1[-4:-9:-1]

i,j,k negativo:


array([12, 11, 10,  9,  8])

#### Generamos un array de 2 dimensiones:
en este caso, si la matriz es $M[rows,cols]$, puedo indicar los parámetros $i,j,k$ tanto para _rows_ como para _cols_ 

In [16]:
arr2d = np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
print('Dimensiones:')
arr2d.shape

Dimensiones:


(5, 4)

In [18]:
print('1er fila:')
arr2d[0]

1er fila:


array([0, 1, 2, 3])

In [19]:
print('2da fila:')
arr2d[1]

2da fila:


array([4, 5, 6, 7])

In [20]:
print('ultima fila:')
arr2d[4]

ultima fila:


array([16, 17, 18, 19])

In [21]:
print('Otra forma de seleccionar la ultima fila:')
arr2d[-1]

Otra forma de seleccionar la ultima fila:


array([16, 17, 18, 19])

In [22]:
print('Otra forma de seleccionar la fila:')
arr2d[arr2d.shape[0]-1]

Otra forma de seleccionar la fila:


array([16, 17, 18, 19])

In [23]:
print('Selecciono las filas 2 y 3')
arr2d[1:3]

Selecciono las filas 2 y 3


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
print('Selecciono las filas 1, 3 y 5, indicando el paso (k)')
arr2d[0:5:2]

Selecciono las filas 1, 3 y 5, indicando el paso (k)


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [25]:
print('Obtengo la 1er. columna de las 3 primeras filas:')
arr2d[0:3,0]

Obtengo la 1er. columna de las 3 primeras filas:


array([0, 4, 8])

In [26]:
print('Obtengo las 2 1ras. columnas de las 3 primeras filas:')
arr2d[0:3,0:2]

Obtengo las 2 1ras. columnas de las 3 primeras filas:


array([[0, 1],
       [4, 5],
       [8, 9]])

In [27]:
print('De las filas impares, obtengo las columnas 2 y 4, indicando el paso k tanto para filas como para columnas:')
arr2d[0:5:2,1:4:2]

De las filas impares, obtengo las columnas 2 y 4, indicando el paso k tanto para filas como para columnas:


array([[ 1,  3],
       [ 9, 11],
       [17, 19]])

In [28]:
print('Slicing con valores por defecto. Indico ":" pero sin i,j,k')
arr2d[::,::]

Slicing con valores por defecto. Indico ":" pero sin i,j,k


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
print('Lo que equivale a k=1')
arr2d[::1]

Lo que equivale a k=1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
print('k=2, en las filas, toma las filas 1,3,5')
arr2d[::2]    # arr2d[::2]

k=2, en las filas, toma las filas 1,3,5


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [31]:
print('k=2 para rows y k=3 para cols. \nToma las filas 1, 3 y 5 y las columas 1 y 4:')
arr2d[::2,::3] 

k=2 para rows y k=3 para cols. 
Toma las filas 1, 3 y 5 y las columas 1 y 4:


array([[ 0,  3],
       [ 8, 11],
       [16, 19]])

In [32]:
print('k=-2 para rows y k=-3 para cols. \nToma las filas 5, 3 y 1 y las columas 4 y 1:')
arr2d[::-2,::-3] 

k=-2 para rows y k=-3 para cols. 
Toma las filas 5, 3 y 1 y las columas 4 y 1:


array([[19, 16],
       [11,  8],
       [ 3,  0]])